<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Regression and Categorical Variables | A Minimal Book Example</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Regression and Categorical Variables | A Minimal Book Example" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Regression and Categorical Variables | A Minimal Book Example" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Yihui Xie" />


<meta name="date" content="2021-05-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="references.html"/>
<link rel="next" href="anova-tutorial.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="literature.html"><a href="literature.html"><i class="fa fa-check"></i><b>3</b> Literature</a></li>
<li class="chapter" data-level="4" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>4</b> Methods</a></li>
<li class="chapter" data-level="5" data-path="applications.html"><a href="applications.html"><i class="fa fa-check"></i><b>5</b> Applications</a><ul>
<li class="chapter" data-level="5.1" data-path="applications.html"><a href="applications.html#example-one"><i class="fa fa-check"></i><b>5.1</b> Example one</a></li>
<li class="chapter" data-level="5.2" data-path="applications.html"><a href="applications.html#example-two"><i class="fa fa-check"></i><b>5.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>6</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="7" data-path="regression-and-categorical-variables.html"><a href="regression-and-categorical-variables.html"><i class="fa fa-check"></i><b>7</b> Regression and Categorical Variables</a></li>
<li class="chapter" data-level="8" data-path="anova-tutorial.html"><a href="anova-tutorial.html"><i class="fa fa-check"></i><b>8</b> ANOVA Tutorial</a></li>
<li class="chapter" data-level="9" data-path="step-1-make-up-data.html"><a href="step-1-make-up-data.html"><i class="fa fa-check"></i><b>9</b> Step 1: Make up Data</a></li>
<li class="chapter" data-level="10" data-path="checking-the-assumptions.html"><a href="checking-the-assumptions.html"><i class="fa fa-check"></i><b>10</b> Checking the Assumptions</a><ul>
<li class="chapter" data-level="10.1" data-path="checking-the-assumptions.html"><a href="checking-the-assumptions.html#checking-assumption-1"><i class="fa fa-check"></i><b>10.1</b> Checking Assumption 1</a></li>
<li class="chapter" data-level="10.2" data-path="checking-the-assumptions.html"><a href="checking-the-assumptions.html#assumption-1-was-violated."><i class="fa fa-check"></i><b>10.2</b> Assumption 1 was violated.</a></li>
<li class="chapter" data-level="10.3" data-path="checking-the-assumptions.html"><a href="checking-the-assumptions.html#checking-assumption-2"><i class="fa fa-check"></i><b>10.3</b> Checking Assumption 2</a></li>
<li class="chapter" data-level="10.4" data-path="checking-the-assumptions.html"><a href="checking-the-assumptions.html#assumption-2-was-violated."><i class="fa fa-check"></i><b>10.4</b> Assumption 2 was violated.</a></li>
<li class="chapter" data-level="10.5" data-path="checking-the-assumptions.html"><a href="checking-the-assumptions.html#checking-assumption-3"><i class="fa fa-check"></i><b>10.5</b> Checking Assumption 3</a></li>
<li class="chapter" data-level="10.6" data-path="checking-the-assumptions.html"><a href="checking-the-assumptions.html#assumption-3-was-violated."><i class="fa fa-check"></i><b>10.6</b> Assumption 3 was violated.</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Minimal Book Example</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression-and-categorical-variables" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Regression and Categorical Variables</h1>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="regression-and-categorical-variables.html#cb4-1"></a><span class="kw">library</span>(tidymodels)</span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;tune&#39;:
##   method                   from   
##   required_pkgs.model_spec parsnip</code></pre>
<pre><code>## ── Attaching packages ────────────────────────────────────── tidymodels 0.1.3 ──</code></pre>
<pre><code>## ✓ broom        0.7.6      ✓ recipes      0.1.16
## ✓ dials        0.0.9      ✓ rsample      0.1.0 
## ✓ dplyr        1.0.6      ✓ tibble       3.1.2 
## ✓ ggplot2      3.3.3      ✓ tidyr        1.1.3 
## ✓ infer        0.5.4      ✓ tune         0.1.5 
## ✓ modeldata    0.1.0      ✓ workflows    0.2.2 
## ✓ parsnip      0.1.6      ✓ workflowsets 0.0.2 
## ✓ purrr        0.3.4      ✓ yardstick    0.0.8</code></pre>
<pre><code>## ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
## x purrr::discard() masks scales::discard()
## x dplyr::filter()  masks stats::filter()
## x dplyr::lag()     masks stats::lag()
## x recipes::step()  masks stats::step()
## • Use tidymodels_prefer() to resolve common conflicts.</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="regression-and-categorical-variables.html#cb9-1"></a><span class="kw">library</span>(ggplot2)</span></code></pre></div>
<p>There is a profound connection between linear regression and ANOVA. In order to see this, you have to understand that the categorical variables of an ANOVA can be coded with numbers, which allows them to be used in a linear regression model. Let us recall the multiple linear regression model.</p>
<p>Given a random sample of <span class="math inline">\(n\)</span> observations
<span class="math inline">\((Y_{i}, X_{i1}, . . ., X_{ip}),\ i=1,...,n\)</span>, the basic multiple linear regression model is
<span class="math display">\[
Y_{i}=\beta_0+\beta_1X_{i1}+...+\beta_pX_{ip}+\epsilon_i,\quad i=1,...,n
\]</span>
where each <span class="math inline">\(\epsilon_i\)</span> is a random variable with a mean of <span class="math inline">\(0\)</span>. In matrix form, this can be written as
<span class="math display">\[
\begin{bmatrix}
Y_1\\
Y_2\\
\vdots\\
Y_n
\end{bmatrix}
= 
\begin{bmatrix}
1 &amp; X_{1,1} &amp; X_{1,2} &amp; \dots &amp; X_{1, p}\\
1 &amp; X_{2,1} &amp; X_{2,2} &amp; \dots &amp; X_{2, p}\\
\vdots &amp; \vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
1 &amp; X_{n,1} &amp; X_{n,2} &amp; \dots &amp; X_{n, p}\\
\end{bmatrix}
\begin{bmatrix}
\beta_0\\
\beta_1\\
\vdots\\
\beta_p\\
\end{bmatrix}
+
\begin{bmatrix}
\epsilon_0\\
\epsilon_1\\
\vdots\\
\epsilon_n\\
\end{bmatrix}
\]</span></p>
<p>Here, the <span class="math inline">\(X_{i,j}\)</span> represent our coded categorical variables. These categorical variables are coded according to the hypotheses of interest. In many cases, the coding is done so that the newly coded variables are contrasts of the old categorical variables.</p>
<p>A contrast is a linear combination of variables such that the coefficients sum to 0.
<span class="math display">\[\sum_i{a_i\theta_i}\quad\text{such that}\quad\sum_i{a_i}=0\]</span></p>
<p>Unlike in ANOVA, iN regression, it is best to use coding schemes based on orthogonal and fractional contrasts. Orthogonal contrasts are a set of contrasts in which, for any distinct pair, the sum of the cross-products of the coefficients is 0.
<span class="math display">\[\sum_i{a_ib_i}=0\]</span></p>
<p>I believe that a fractional contrast is such that
<span class="math display">\[\sum_i{|a_i|}=2\]</span></p>
<p>Categorical variable coding schemes can be easily expressed in a matrix format. The convention is to have the old categorical variables as the row headers and the newly coded variables as the column headers. In such a matrix, the <span class="math inline">\([c_{ij}]\)</span> entry indicates the value of the <span class="math inline">\(j^{th}\)</span> level of the new variable for the <span class="math inline">\(i^{th}\)</span> level of the old variable. Here is an example of such a matrix constructed using orthogonal and fractional contrasts.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="regression-and-categorical-variables.html#cb10-1"></a>(<span class="dt">contr_mat =</span> <span class="kw">matrix</span>(<span class="dt">data =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="op">-</span><span class="dv">1</span>,<span class="fl">0.5</span>,<span class="op">-</span><span class="dv">1</span>,<span class="fl">0.5</span>), <span class="dt">nrow =</span> <span class="dv">3</span>, <span class="dt">ncol =</span> <span class="dv">2</span>))</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1  0.5
## [2,]    0 -1.0
## [3,]   -1  0.5</code></pre>
<p>Interpreting this coding scheme in the context of our linear model, we see that</p>
<p><span class="math display">\[
\begin{aligned}
E(Y_i|X_{i1}=1,X_{i2}=\tfrac{1}{2}) &amp;= \beta_0+\beta_1+\tfrac{1}{2}\beta_2 &amp;= \mu_1 \\
E(Y_i|X_{i1}=0,X_{i2}=-1) &amp;= \beta_0-\beta_2 &amp;= \mu_2\\
E(Y_i|X_{i1}=-1,X_{i2}=\tfrac{1}{2}) &amp;= \beta_0-\beta_1+\tfrac{1}{2}\beta_2 &amp;= \mu_3
\end{aligned}
\]</span></p>
<p>or, in matrix format,
<span class="math display">\[
\begin{bmatrix}
1 &amp; 1 &amp; \tfrac{1}{2} \\
1 &amp; 0 &amp; -1 \\
1 &amp; -1 &amp; \tfrac{1}{2}
\end{bmatrix}
\begin{bmatrix}
\beta_0 \\
\beta_1  \\
\beta_2 
\end{bmatrix}
=
\begin{bmatrix}
\mu_1 \\
\mu_2  \\
\mu_3 
\end{bmatrix}
\]</span></p>
<p>We can solve this for <span class="math inline">\(\boldsymbol{\beta}\)</span> for interpretation’s sake.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="regression-and-categorical-variables.html#cb12-1"></a><span class="kw">solve</span>(<span class="kw">cbind</span>(<span class="kw">rep</span>(<span class="dv">1</span>, <span class="kw">nrow</span>(contr_mat)), contr_mat))</span></code></pre></div>
<pre><code>##           [,1]       [,2]       [,3]
## [1,] 0.3333333  0.3333333  0.3333333
## [2,] 0.5000000  0.0000000 -0.5000000
## [3,] 0.3333333 -0.6666667  0.3333333</code></pre>
<p><span class="math display">\[
\begin{aligned}
\beta_0 &amp;= \tfrac{\mu_1+\mu_2+\mu_3}{3} = \text{grand mean response} \\
2\beta_1 &amp;= \mu_1 - \mu_3  = \text{difference in the mean response between levels 1 &amp; 3 of the old categorical variable}\\
\tfrac{3}{2}\beta_2 &amp;= \tfrac{\mu_1+\mu_3}{2} - \mu_2 = \text{difference in the mean response between the average of levels 1 &amp; 3 and level 2 of the old categorical variable}
\end{aligned}
\]</span></p>
<p>Let’s look at another contrast matrix and see if we can interpret it.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="regression-and-categorical-variables.html#cb14-1"></a><span class="kw">contr.helmert</span>(<span class="dt">n =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##   [,1] [,2]
## 1   -1   -1
## 2    1   -1
## 3    0    2</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="regression-and-categorical-variables.html#cb16-1"></a><span class="kw">solve</span>(<span class="kw">cbind</span>(<span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="kw">contr.helmert</span>(<span class="dt">n =</span> <span class="dv">3</span>)))</span></code></pre></div>
<pre><code>##               1          2         3
## [1,]  0.3333333  0.3333333 0.3333333
## [2,] -0.5000000  0.5000000 0.0000000
## [3,] -0.1666667 -0.1666667 0.3333333</code></pre>
<p><span class="math display">\[
\begin{aligned}
\beta_0 &amp;= \tfrac{\mu_1+\mu_2+\mu_3}{3} = \text{grand mean response} \\
2\beta_1 &amp;= \mu_2 - \mu_1  = \text{difference in the mean response between levels 2 &amp; 1 of the old categorical variable}\\
3\beta_2 &amp;= \mu_3 - \tfrac{\mu_1+\mu_2}{2} = \text{difference in the mean response between level 3 and the average of levels 1 &amp; 2 of the old categorical variable}
\end{aligned}
\]</span></p>
<p>Perhaps you have heard of polynomial regression? Polynomial regression is just a special case of linear regression in a different basis. In polynomial regression, (just like multiple linear regression) if you use all of your explanatory variables, then you will likely get multi-collinearity problems.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="regression-and-categorical-variables.html#cb18-1"></a><span class="kw">contr.poly</span>(<span class="dt">n=</span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>##                 .L         .Q
## [1,] -7.071068e-01  0.4082483
## [2,] -7.850462e-17 -0.8164966
## [3,]  7.071068e-01  0.4082483</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="regression-and-categorical-variables.html#cb20-1"></a>(<span class="dt">A =</span> <span class="kw">solve</span>(<span class="kw">cbind</span>(<span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="kw">contr.poly</span>(<span class="dt">n=</span><span class="dv">3</span>))))</span></code></pre></div>
<pre><code>##          [,1]       [,2]      [,3]
##     0.3333333  0.3333333 0.3333333
## .L -0.7071068  0.0000000 0.7071068
## .Q  0.4082483 -0.8164966 0.4082483</code></pre>
<p>The first matrix shows how to code the levels of your categorical variable and the second matrix is used for interpretation.</p>
<p><span class="math display">\[
\begin{aligned}
\beta_0 &amp;= \tfrac{\mu_1+\mu_2+\mu_3}{3} = \text{grand mean response} \\
\beta_1 &amp;= -0.707\mu_1 + 0.707\mu_3  = \text{measure of a linear trend in the mean response}\\
\beta_2 &amp;= 0.408 \mu_3 - 0.816 \mu_2 + 0.408 \mu3 = \text{measure of a quadratic trend in the mean response}
\end{aligned}
\]</span></p>
<p>For example, we can test whether the difference between the means from two populations are equal by doing a linear regression or an ANOVA.</p>
<p>Let’s make up some data and try it!</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="regression-and-categorical-variables.html#cb22-1"></a><span class="kw">source</span>(<span class="kw">file.path</span>(<span class="st">&quot;R-source-code&quot;</span>, <span class="st">&quot;fabricate.R&quot;</span>))</span>
<span id="cb22-2"><a href="regression-and-categorical-variables.html#cb22-2"></a></span>
<span id="cb22-3"><a href="regression-and-categorical-variables.html#cb22-3"></a>design =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">group =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="dt">n =</span> <span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">10</span>))</span>
<span id="cb22-4"><a href="regression-and-categorical-variables.html#cb22-4"></a></span>
<span id="cb22-5"><a href="regression-and-categorical-variables.html#cb22-5"></a>data1 =<span class="st"> </span><span class="kw">fabricate</span>(<span class="dt">flr =</span> design)</span></code></pre></div>
<p>Let’s check out our data.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="regression-and-categorical-variables.html#cb23-1"></a><span class="co"># Make a linear model</span></span>
<span id="cb23-2"><a href="regression-and-categorical-variables.html#cb23-2"></a>data1_lm_independent_samples =<span class="st"> </span><span class="kw">lm</span>(response <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> data1)</span>
<span id="cb23-3"><a href="regression-and-categorical-variables.html#cb23-3"></a></span>
<span id="cb23-4"><a href="regression-and-categorical-variables.html#cb23-4"></a><span class="co"># plot</span></span>
<span id="cb23-5"><a href="regression-and-categorical-variables.html#cb23-5"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> data1,</span>
<span id="cb23-6"><a href="regression-and-categorical-variables.html#cb23-6"></a>       <span class="kw">aes</span>(<span class="dt">x =</span> group,</span>
<span id="cb23-7"><a href="regression-and-categorical-variables.html#cb23-7"></a>       <span class="dt">y =</span> response,</span>
<span id="cb23-8"><a href="regression-and-categorical-variables.html#cb23-8"></a>       <span class="dt">color =</span> <span class="kw">factor</span>(group))) <span class="op">+</span></span>
<span id="cb23-9"><a href="regression-and-categorical-variables.html#cb23-9"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb23-10"><a href="regression-and-categorical-variables.html#cb23-10"></a><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">height =</span> <span class="dv">0</span>, <span class="dt">width =</span> <span class="fl">0.1</span>) <span class="op">+</span></span>
<span id="cb23-11"><a href="regression-and-categorical-variables.html#cb23-11"></a><span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> data1_lm_independent_samples<span class="op">$</span>coefficients[<span class="dv">1</span>],</span>
<span id="cb23-12"><a href="regression-and-categorical-variables.html#cb23-12"></a>              <span class="dt">slope =</span> data1_lm_independent_samples<span class="op">$</span>coefficients[<span class="dv">2</span>]) <span class="op">+</span></span>
<span id="cb23-13"><a href="regression-and-categorical-variables.html#cb23-13"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Group Comparison from a Regression Standpoint&quot;</span>,</span>
<span id="cb23-14"><a href="regression-and-categorical-variables.html#cb23-14"></a>       <span class="dt">color =</span> <span class="st">&quot;Group&quot;</span>,</span>
<span id="cb23-15"><a href="regression-and-categorical-variables.html#cb23-15"></a>       <span class="dt">x =</span> <span class="st">&quot;Group&quot;</span>,</span>
<span id="cb23-16"><a href="regression-and-categorical-variables.html#cb23-16"></a>       <span class="dt">y =</span> <span class="st">&quot;Response&quot;</span>) <span class="op">+</span></span>
<span id="cb23-17"><a href="regression-and-categorical-variables.html#cb23-17"></a><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span></code></pre></div>
<pre><code>## Warning: Continuous limits supplied to discrete scale.
## Did you mean `limits = factor(...)` or `scale_*_continuous()`?</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The way you code your categorical variables in a linear model is extremely important. Different codings lead to different interpretations of the parameters (betas) in your model. For us, our model is
<span class="math display">\[
Y_i = \beta_0+\beta_{i1}X_{i1}+\epsilon_i
\]</span>
From this, we have
<span class="math display">\[
\begin{aligned}
E(Y_i|X_{i1}=0) &amp;=\beta_0 \\
E(Y_i|X_{i1}=1) &amp;=\beta_0 + \beta_1
\end{aligned}
\]</span>
From which we can derive,
<span class="math display">\[
\beta_1 = E(Y_i|X_{i1}=1) - E(Y_i|X_{i1}=0)
\]</span>
So, our slope estimate is the estimated amount by which the mean of group1 is above that of the mean of group0.</p>
<p>Run linear regression</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="regression-and-categorical-variables.html#cb25-1"></a><span class="kw">summary</span>(data1_lm_independent_samples)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = response ~ group, data = data1)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -6.761 -1.502 -0.346  1.436  5.115 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   3.7250     0.9208   4.045 0.000759 ***
## group        -3.5740     1.3022  -2.745 0.013324 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.912 on 18 degrees of freedom
## Multiple R-squared:  0.295,  Adjusted R-squared:  0.2559 
## F-statistic: 7.533 on 1 and 18 DF,  p-value: 0.01332</code></pre>
<p>Run ANOVA</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="regression-and-categorical-variables.html#cb27-1"></a>data1<span class="op">$</span>group =<span class="st"> </span><span class="kw">as.factor</span>(data1<span class="op">$</span>group)</span>
<span id="cb27-2"><a href="regression-and-categorical-variables.html#cb27-2"></a>data1_ANOVA_independent_samples =<span class="st"> </span><span class="kw">aov</span>(response <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> data1)</span>
<span id="cb27-3"><a href="regression-and-categorical-variables.html#cb27-3"></a><span class="kw">summary</span>(data1_ANOVA_independent_samples)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## group        1  63.87   63.87   7.533 0.0133 *
## Residuals   18 152.61    8.48                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Run t-Test</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="regression-and-categorical-variables.html#cb29-1"></a>(<span class="dt">data1_t_test_independent_samples =</span> <span class="kw">t.test</span>(<span class="dt">x =</span> data1[data1<span class="op">$</span>group <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;response&quot;</span>], <span class="dt">y =</span> data1[data1<span class="op">$</span>group <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;response&quot;</span>], <span class="dt">paired =</span> <span class="ot">FALSE</span>, <span class="dt">var.equal =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  data1[data1$group == 1, &quot;response&quot;] and data1[data1$group == 0, &quot;response&quot;]
## t = -2.7446, df = 18, p-value = 0.01332
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -6.3097714 -0.8382286
## sample estimates:
## mean of x mean of y 
##     0.151     3.725</code></pre>
<p>Notice the similarities.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="regression-and-categorical-variables.html#cb31-1"></a><span class="co"># Confidence interval for the difference in the means</span></span>
<span id="cb31-2"><a href="regression-and-categorical-variables.html#cb31-2"></a><span class="kw">confint</span>(data1_lm_independent_samples, <span class="st">&quot;group&quot;</span>, <span class="dt">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##           2.5 %     97.5 %
## group -6.309771 -0.8382286</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="regression-and-categorical-variables.html#cb33-1"></a>data1_t_test_independent_samples<span class="op">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] -6.3097714 -0.8382286
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="regression-and-categorical-variables.html#cb35-1"></a><span class="co"># p-values</span></span>
<span id="cb35-2"><a href="regression-and-categorical-variables.html#cb35-2"></a><span class="kw">with</span>(<span class="kw">summary</span>(data1_lm_independent_samples), <span class="kw">unname</span>(<span class="kw">pf</span>(fstatistic[<span class="dv">1</span>],fstatistic[<span class="dv">2</span>],fstatistic[<span class="dv">3</span>],<span class="dt">lower.tail=</span>F)))</span></code></pre></div>
<pre><code>## [1] 0.01332393</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="regression-and-categorical-variables.html#cb37-1"></a><span class="kw">summary</span>(data1_ANOVA_independent_samples)[[<span class="dv">1</span>]][[<span class="dv">1</span>, <span class="dv">5</span>]]</span></code></pre></div>
<pre><code>## [1] 0.01332393</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="regression-and-categorical-variables.html#cb39-1"></a>data1_t_test_independent_samples<span class="op">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.01332393</code></pre>
<p>Now, let’s look at something else. The CO2 data frame has 84 rows and 5 columns of data from an experiment on the cold tolerance of the grass species Echinochloa crus-galli.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="regression-and-categorical-variables.html#cb41-1"></a><span class="kw">data</span>(<span class="st">&quot;CO2&quot;</span>)</span>
<span id="cb41-2"><a href="regression-and-categorical-variables.html#cb41-2"></a></span>
<span id="cb41-3"><a href="regression-and-categorical-variables.html#cb41-3"></a>CO2[<span class="kw">sample</span>(<span class="kw">nrow</span>(CO2), <span class="dt">size =</span> <span class="dv">5</span>), ]</span></code></pre></div>
<pre><code>##    Plant        Type  Treatment conc uptake
## 9    Qn2      Quebec nonchilled  175   27.3
## 48   Mn1 Mississippi nonchilled  675   32.4
## 21   Qn3      Quebec nonchilled 1000   45.5
## 25   Qc1      Quebec    chilled  350   34.6
## 27   Qc1      Quebec    chilled  675   35.4</code></pre>
<p>What is a linear model? In the context of linear regression, a linear model is a relationship between the responses and the explanatory variables that is linear in the parameters.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="regression-and-categorical-variables.html#cb43-1"></a>CO2_recipe =<span class="st"> </span><span class="kw">recipe</span>(uptake <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> CO2) <span class="op">%&gt;%</span></span>
<span id="cb43-2"><a href="regression-and-categorical-variables.html#cb43-2"></a><span class="st">  </span><span class="kw">step_dummy</span>(<span class="kw">c</span>(<span class="st">&quot;Type&quot;</span>, <span class="st">&quot;Treatment&quot;</span>))</span>
<span id="cb43-3"><a href="regression-and-categorical-variables.html#cb43-3"></a><span class="co"># see contrasts() function</span></span>
<span id="cb43-4"><a href="regression-and-categorical-variables.html#cb43-4"></a></span>
<span id="cb43-5"><a href="regression-and-categorical-variables.html#cb43-5"></a>CO2_linear_model =<span class="st"> </span><span class="kw">linear_reg</span>() <span class="op">%&gt;%</span></span>
<span id="cb43-6"><a href="regression-and-categorical-variables.html#cb43-6"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;lm&quot;</span>, <span class="dt">contrasts =</span> <span class="kw">list</span>(<span class="dt">Plant =</span> <span class="st">&quot;contr.poly&quot;</span>))</span>
<span id="cb43-7"><a href="regression-and-categorical-variables.html#cb43-7"></a></span>
<span id="cb43-8"><a href="regression-and-categorical-variables.html#cb43-8"></a>CO2_workflow =<span class="st"> </span><span class="kw">workflow</span>() <span class="op">%&gt;%</span></span>
<span id="cb43-9"><a href="regression-and-categorical-variables.html#cb43-9"></a><span class="st">  </span><span class="kw">add_model</span>(CO2_linear_model) <span class="op">%&gt;%</span></span>
<span id="cb43-10"><a href="regression-and-categorical-variables.html#cb43-10"></a><span class="st">  </span><span class="kw">add_recipe</span>(CO2_recipe)</span>
<span id="cb43-11"><a href="regression-and-categorical-variables.html#cb43-11"></a></span>
<span id="cb43-12"><a href="regression-and-categorical-variables.html#cb43-12"></a>CO2_fit =<span class="st"> </span>CO2_workflow <span class="op">%&gt;%</span></span>
<span id="cb43-13"><a href="regression-and-categorical-variables.html#cb43-13"></a><span class="st">  </span><span class="kw">fit</span>(<span class="dt">data =</span> CO2)</span></code></pre></div>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="regression-and-categorical-variables.html#cb44-1"></a>CO2_fit <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb44-2"><a href="regression-and-categorical-variables.html#cb44-2"></a><span class="st">  </span><span class="kw">pull_workflow_fit</span>() <span class="op">%&gt;%</span></span>
<span id="cb44-3"><a href="regression-and-categorical-variables.html#cb44-3"></a><span class="st">  </span><span class="kw">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 15 x 5
##    term              estimate std.error statistic   p.value
##    &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1 (Intercept)        19.5      1.17      16.7     2.96e-26
##  2 Plant.L           -22.9      2.27     -10.1     2.17e-15
##  3 Plant.Q            -4.62     2.27      -2.03    4.57e- 2
##  4 Plant.C             4.67     2.27       2.06    4.34e- 2
##  5 Plant^4             2.34     2.27       1.03    3.06e- 1
##  6 Plant^5             4.31     2.27       1.90    6.13e- 2
##  7 Plant^6            -0.0390   2.27      -0.0172  9.86e- 1
##  8 Plant^7            -2.04     2.27      -0.897   3.73e- 1
##  9 Plant^8            -3.28     2.27      -1.44    1.53e- 1
## 10 Plant^9            -9.07     2.27      -4.00    1.56e- 4
## 11 Plant^10            0.546    2.27       0.241   8.10e- 1
## 12 Plant^11            1.91     2.27       0.843   4.02e- 1
## 13 conc                0.0177   0.00223    7.96    1.97e-11
## 14 Type_Mississippi   NA       NA         NA      NA       
## 15 Treatment_chilled  NA       NA         NA      NA</code></pre>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="references.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="anova-tutorial.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/07-regression-and-categorical-variables.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
